export enum CustomErrors {
  REFRESH_EXPIRED = 'REFRESH_EXPIRED',
  ACCESS_EXPIRED = 'ACCESS_EXPIRED',
  DEFAULT_EXPIRED = 'DEFAULT_EXPIRED',
  JWT_ERROR = 'JWT_ERROR',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
}